#!/usr/bin/env bash
# step2_ANTs_registration_apply_affine_inversewarp_to_template_space_label_map.sh
# Take a template-space label map (already aligned to your population template space)
# and reverse-warp it back to each subject native space using:
#   1) subject-specific InverseWarp (template -> subject)
#   2) inverse of subject-specific Affine (template -> subject)
#
# This script is designed to pair with the previous template-building script output tree as generated by step1:
#   <POP_TEMPLATE_OUT_DIR>/output/01_warps              (Affine + InverseWarp live here)
#   <POP_TEMPLATE_OUT_DIR>/output/02_warped-input       (final template lives here)
#
# Uses nearest-neighbor interpolation for label safety.

set -euo pipefail
IFS=$'\n\t'

###############################################################################
# Defaults (sample placeholders)
###############################################################################
# Template-space label maps (in population template space)
TEMPLATE_LABEL_NONLR="/path/to/population_template_space/ABA_labels_in_population_template_space.nii.gz"
TEMPLATE_LABEL_LR="/path/to/population_template_space/ABA_labels_in_population_template_space_LR_separated.nii.gz"

# Where transforms are saved by the template-building script
# This should be: <POP_TEMPLATE_OUT_DIR>/output/01_warps
WARP_DIR="/path/to/population_template_out/output/01_warps"

# Native-space reference images for each subject (the grid you want labels resampled onto)
# This should contain the SAME filenames used when building the template (or compatible basenames).
REF_DIR="/path/to/subject_native_mean_images"

# Output directories for subject-space label maps
OUT_DIR_NONLR="/path/to/subject_level_labels/nonLR"
OUT_DIR_LR="/path/to/subject_level_labels/LR_separated"

# Behavior switches
FORCE="0"                 # 1 = overwrite existing outputs
DRY_RUN="0"               # 1 = print commands only
SKIP_LR="0"               # 1 = do not process LR map

###############################################################################
# Helpers
###############################################################################
usage() {
  cat <<'EOF'
Usage:
  ants_reversewarp_labelmaps_to_subjects.sh \
    -a TEMPLATE_LABEL_NONLR \
    [-b TEMPLATE_LABEL_LR] \
    -w WARP_DIR \
    -r REF_DIR \
    -o OUT_DIR_NONLR \
    [-l OUT_DIR_LR] \
    [--skip-lr] \
    [--force] \
    [--dry-run]

Required:
  -a  Template-space non-LR label map (NIfTI)
  -w  Warp directory from template build, usually:
        <POP_TEMPLATE_OUT_DIR>/output/01_warps
  -r  Reference image directory in subject native space
  -o  Output directory for non-LR subject-space labels

Optional:
  -b  Template-space LR-separated label map (NIfTI)
  -l  Output directory for LR-separated subject-space labels
  --skip-lr   Skip LR map processing (if you only have non-LR)
  --force     Overwrite outputs if they exist
  --dry-run   Print commands without executing

Expected files inside WARP_DIR (from buildtemplateparallel.sh):
  warped_<SUBJECT_BASENAME>Affine.txt
  warped_<SUBJECT_BASENAME>InverseWarp.nii.gz

How transform naming is interpreted:
  SUBJECT_BASENAME is derived from:
    warped_<SUBJECT_BASENAME>Affine.txt  (strip "warped_" prefix, strip "Affine.txt" suffix)
  Reference image is expected at:
    REF_DIR/<SUBJECT_BASENAME>.nii.gz
  Outputs are written to:
    OUT_DIR_NONLR/<SUBJECT_BASENAME>_ABA_labels.nii.gz
    OUT_DIR_LR/<SUBJECT_BASENAME>_ABA_labels_LR_separated.nii.gz

Example (generic):
  ./ants_reversewarp_labelmaps_to_subjects.sh \
    -a /data/template_space/ABA_labels.nii.gz \
    -b /data/template_space/ABA_labels_LR.nii.gz \
    -w /data/pop_template/output/01_warps \
    -r /data/subject_means \
    -o /data/subject_labels/nonLR \
    -l /data/subject_labels/LR

EOF
}

log() { echo "[$(date '+%F %T')] $*"; }

die() { echo "[FATAL] $*" 1>&2; exit 1; }

run() {
  if [ "$DRY_RUN" = "1" ]; then
    echo "[DRY-RUN] $*"
  else
    eval "$@"
  fi
}

check_file() { [ -f "$1" ] || die "File not found: $1"; }

check_dir() { [ -d "$1" ] || die "Directory not found: $1"; }

has_cmd() { command -v "$1" >/dev/null 2>&1; }

###############################################################################
# Args
###############################################################################
while [ $# -gt 0 ]; do
  case "$1" in
    -a) TEMPLATE_LABEL_NONLR="$2"; shift 2 ;;
    -b) TEMPLATE_LABEL_LR="$2"; shift 2 ;;
    -w) WARP_DIR="$2"; shift 2 ;;
    -r) REF_DIR="$2"; shift 2 ;;
    -o) OUT_DIR_NONLR="$2"; shift 2 ;;
    -l) OUT_DIR_LR="$2"; shift 2 ;;
    --skip-lr) SKIP_LR="1"; shift 1 ;;
    --force) FORCE="1"; shift 1 ;;
    --dry-run) DRY_RUN="1"; shift 1 ;;
    -h|--help) usage; exit 0 ;;
    *) die "Unknown argument: $1 (use -h for help)" ;;
  esac
done

###############################################################################
# Validations
###############################################################################
check_file "$TEMPLATE_LABEL_NONLR"
check_dir "$WARP_DIR"
check_dir "$REF_DIR"

if [ "$SKIP_LR" != "1" ]; then
  check_file "$TEMPLATE_LABEL_LR"
  [ -n "$OUT_DIR_LR" ] || die "LR output dir (-l) is required unless --skip-lr is set."
fi

run "mkdir -p \"$OUT_DIR_NONLR\""
if [ "$SKIP_LR" != "1" ]; then
  run "mkdir -p \"$OUT_DIR_LR\""
fi

# Prefer antsApplyTransforms when available, otherwise fall back to WarpImageMultiTransform.
# Both support nearest-neighbor interpolation for label maps.
ENGINE=""
if has_cmd antsApplyTransforms; then
  ENGINE="antsApplyTransforms"
elif has_cmd WarpImageMultiTransform; then
  ENGINE="WarpImageMultiTransform"
else
  die "Neither antsApplyTransforms nor WarpImageMultiTransform found in PATH. Load ANTs or fix PATH."
fi

log "ENGINE                = $ENGINE"
log "TEMPLATE_LABEL_NONLR   = $TEMPLATE_LABEL_NONLR"
if [ "$SKIP_LR" != "1" ]; then log "TEMPLATE_LABEL_LR      = $TEMPLATE_LABEL_LR"; fi
log "WARP_DIR               = $WARP_DIR"
log "REF_DIR                = $REF_DIR"
log "OUT_DIR_NONLR          = $OUT_DIR_NONLR"
if [ "$SKIP_LR" != "1" ]; then log "OUT_DIR_LR             = $OUT_DIR_LR"; fi
log "FORCE                  = $FORCE"
log "DRY_RUN                = $DRY_RUN"
log "SKIP_LR                = $SKIP_LR"
echo

###############################################################################
# Main loop over subjects
###############################################################################
shopt -s nullglob
AFF_FILES=( "$WARP_DIR"/warped_*Affine.txt )
shopt -u nullglob

[ "${#AFF_FILES[@]}" -gt 0 ] || die "No warped_*Affine.txt found in: $WARP_DIR"

for AFF in "${AFF_FILES[@]}"; do
  AFF_BASENAME="$(basename "$AFF")"                 # warped_<SUBJECT_BASENAME>Affine.txt
  STEM="${AFF_BASENAME%Affine.txt}"                 # warped_<SUBJECT_BASENAME>
  INVWARP="$WARP_DIR/${STEM}InverseWarp.nii.gz"     # warped_<SUBJECT_BASENAME>InverseWarp.nii.gz

  SUBJECT_BASENAME="${STEM#warped_}"                # <SUBJECT_BASENAME>
  REF_IMG="$REF_DIR/${SUBJECT_BASENAME}.nii.gz"     # native-space reference image

  OUT_NONLR="$OUT_DIR_NONLR/${SUBJECT_BASENAME}_ABA_labels.nii.gz"
  OUT_LR="$OUT_DIR_LR/${SUBJECT_BASENAME}_ABA_labels_LR_separated.nii.gz"

  if [ ! -f "$INVWARP" ]; then
    log "[SKIP] Missing inverse warp: $INVWARP"
    continue
  fi

  if [ ! -f "$REF_IMG" ]; then
    log "[SKIP] Missing reference image: $REF_IMG"
    continue
  fi

  log "SUBJECT = $SUBJECT_BASENAME"
  log "  AFF    = $AFF"
  log "  INVW   = $INVWARP"
  log "  REF    = $REF_IMG"

  # Non-LR
  if [ -f "$OUT_NONLR" ] && [ "$FORCE" != "1" ]; then
    log "  [SKIP] Non-LR exists: $OUT_NONLR"
  else
    log "  Writing non-LR: $OUT_NONLR"
    if [ "$ENGINE" = "antsApplyTransforms" ]; then
      # antsApplyTransforms applies transforms in reverse order of listing.
      # We want: template -> subject = InverseWarp then inverse(Affine).
      # Therefore list: -t [Affine,1] then -t InverseWarp, so it applies InverseWarp first.
      run "antsApplyTransforms -d 3 \
        -i \"$TEMPLATE_LABEL_NONLR\" \
        -r \"$REF_IMG\" \
        -o \"$OUT_NONLR\" \
        -n NearestNeighbor \
        -t [\"$AFF\",1] \
        -t \"$INVWARP\""
    else
      # WarpImageMultiTransform form, consistent with your original script.
      run "WarpImageMultiTransform 3 \
        \"$TEMPLATE_LABEL_NONLR\" \
        \"$OUT_NONLR\" \
        -R \"$REF_IMG\" \
        -i \"$AFF\" \
        \"$INVWARP\" \
        --use-NN"
    fi
  fi

  # LR-separated
  if [ "$SKIP_LR" = "1" ]; then
    log "  [SKIP] LR processing disabled (--skip-lr)."
  else
    if [ -f "$OUT_LR" ] && [ "$FORCE" != "1" ]; then
      log "  [SKIP] LR exists: $OUT_LR"
    else
      log "  Writing LR: $OUT_LR"
      if [ "$ENGINE" = "antsApplyTransforms" ]; then
        run "antsApplyTransforms -d 3 \
          -i \"$TEMPLATE_LABEL_LR\" \
          -r \"$REF_IMG\" \
          -o \"$OUT_LR\" \
          -n NearestNeighbor \
          -t [\"$AFF\",1] \
          -t \"$INVWARP\""
      else
        run "WarpImageMultiTransform 3 \
          \"$TEMPLATE_LABEL_LR\" \
          \"$OUT_LR\" \
          -R \"$REF_IMG\" \
          -i \"$AFF\" \
          \"$INVWARP\" \
          --use-NN"
      fi
    fi
  fi

  echo
done

log "All done."